#!/usr/bin/env bash

#  Copyright (c) 2023. Lantern Pharma Inc. All rights reserved.

set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
python -u logistic_fe_aug.py "$@"
python -u rf_fe_aug.py "$@"
python -u dnn_fe_aug.py "$@"
python -u ensemble.py "$@"

