name: tdc
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.9.12
  - pycurl=7.45.1
  - rdkit=2022.9.3
  - pytorch=1.13.1
  - optuna=3.1.0
  - lightgbm=3.3.5
  - boto3=1.26.8
  - keras-tuner=1.2.1
  - tensorflow=2.11.0
  - pip
  - pip:
    - dgl==0.9.1
    - ipywidgets==8.0.4
    - karateclub==1.3.3
    - ogb==1.3.5
    - pybel==0.15.5
    - pytdc==0.3.8
    - rdkit==2022.9.3
    - scikit-learn==1.2.0
    - spektral==1.2.0
    - torch-geometric==2.2.0
    - imblearn==0.0
    - matplotlib==3.7.0
    - mlflow==1.30.0
    - seaborn==0.12.2
    - shap==0.41.0
    - git+https://github.com/samoturk/mol2vec