# hash:sha256:44c33664d297caaa4b9d83c71ab80d0800d21514b7eb6aa8e2703b41bad606c2
FROM codeocean/jupyterlab:3.4.4-miniconda4.12.0-python3.9-ubuntu20.04

ARG DEBIAN_FRONTEND=noninteractive

# Note: Required for private Code Ocean deployment
#FROM registry.codeocean-ue2.radr-ai.com/codeocean/jupyterlab:3.4.4-miniconda4.12.0-python3.9-ubuntu20.04
#ARG GIT_ASKPASS
#ARG GIT_ACCESS_TOKEN
#COPY git-askpass /

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        libxi6=2:1.7.10-0ubuntu1 \
        libxrender1=1:0.9.10-1 \
        libxtst6=2:1.2.3-1 \
    && rm -rf /var/lib/apt/lists/*

RUN conda install -y --channel=conda-forge \
        pycurl==7.45.1 \
    && conda clean -ya

RUN pip install -U --no-cache-dir \
    dgl==0.9.1 \
    ipywidgets==8.0.4 \
    karateclub==1.3.3 \
    ogb==1.3.5 \
    pybel==0.15.5 \
    pytdc==0.3.8 \
    rdkit==2022.9.3 \
    scikit-learn==1.2.0 \
    spektral==1.2.0 \
    torch-geometric==2.2.0

RUN pip3 install -U --no-cache-dir \
    boto3==1.26.8 \
    imblearn==0.0 \
    keras-tuner==1.2.1 \
    lightgbm==3.3.5 \
    matplotlib==3.7.0 \
    mlflow==1.30.0 \
    optuna==3.1.0 \
    seaborn==0.12.2 \
    shap==0.41.0 \
    tensorflow==2.11.0 \
    torch==1.13.1 \
    torch-cluster==1.6.0 \
    torch-scatter==2.1.0 \
    torch-sparse==0.6.16 \
    torchvision==0.14.1

RUN pip install git+https://github.com/samoturk/mol2vec

# Note: Required for private Code Ocean deployment
# COPY postInstall /
# RUN /postInstall
